const Super_admin = {
     "id_instituicao": "",
     "nome": "Superman",
     "sobrenome": "Kent",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": true,
     "desconto_max": 100,
     "cpf": "15962611020",
     "rg": "387965439",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "superman@dc.com",
     "perfis": ["SUPER_ADMIN"],
     "perfil_atual": "SUPER_ADMIN",
     "senha": "",
     "pais": "Brasil",
     "estado": "São Paulo",
     "cidade": "São Paulo",
     "bairro": "Morumbi",
     "logradouro": "Av. Morumbi",
     "numero": 1000,
     "cep": "05892470"

}

const admin = {
     "id_instituicao": "",
     "nome": "Batman",
     "sobrenome": "Wayne",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": true,
     "desconto_max": 10,
     "cpf": "83887126084",
     "rg": "392284182",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "startupdobem@gmail.com",
     "perfis": ["ADMIN"],
     "perfil_atual": "ADMIN",
     "senha": "",
     "pais": "Brasil",
     "estado": "São Paulo",
     "cidade": "São Paulo",
     "bairro": "Centro",
     "logradouro": "Rua 25 de Março",
     "numero": 200,
     "cep": "05892470",
     "financas": [],

}


const diretor = {
     "id_instituicao": "",
     "id_escola": "",
     "nome": "Aquaman",
     "sobrenome": "Curry",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": true,
     "desconto_max": 10,
     "cpf": "28268111003",
     "rg": "226715851",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "aquaman@dc.com",
     "perfis": ["DIRETOR"],
     "perfil_atual": "DIRETOR",
     "senha": "",
     "pais": "Brasil",
     "estado": "São Paulo",
     "cidade": "São Paulo",
     "bairro": "Itaim",
     "logradouro": "Casa do ator",
     "numero": 202,
     "cep": "05892470"

}



const professor = {
     "id_instituicao": "O7EYbAkzlMuZaiHBzJ5l",
     "id_escola": "5QWPp86CobgBWrgQqHKp",
     "nome": "Ciborgue",
     "sobrenome": "Stone",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": false,
     "desconto_max": 0,
     "cpf": "15842166038",
     "rg": "425295163",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "ciborgue@dc.com.br",
     "perfis": ["PROFESSOR"],
     "perfil_atual": "PROFESSOR",
     "senha": "",
     "pais": "Brasil",
     "estado": "São Paulo",
     "cidade": "São Paulo",
     "bairro": "Bela Vista",
     "logradouro": "Rua California",
     "numero": 978,
     "cep": "05892470",
     "disciplinas": [],
     "turmas": [],
     "financas": []

}


const filiacao = {
     "id_instituicao": "",
     "id_escola": "",
     "nome": "Henry",
     "sobrenome": "Allen",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": false,
     "desconto_max": 0,
     "cpf": "92135508047",
     "rg": "377201042",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "henry@dc.com",
     "perfis": ["FILIACAO"],
     "perfil_atual": "FILIACAO",
     "senha": "",
     "pais": "Brasil",
     "estado": "São Paulo",
     "cidade": "São Paulo",
     "bairro": "Pinheiros",
     "logradouro": "Rua Arco verde",
     "numero": 356,
     "cep": "5892470",
     "turmas": [],
     "filhos": [],
     "financas": [],

}

const aluno = {
     "id_instituicao": "",
     "id_escola": "",
     "nome": "Flash",
     "sobrenome": "Allen",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": false,
     "desconto_max": 0,
     "cpf": "01248928091",
     "rg": "216560809",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "flash@dc.com",
     "perfis": ["ALUNO"],
     "perfil_atual": "ALUNO",
     "senha": "",
     "pais": "Brasil",
     "estado": "São Paulo",
     "cidade": "São Paulo",
     "bairro": "Pinheiros",
     "logradouro": "Rua Arco verde",
     "numero":356,
     "cep": "05892470",
     "filiacoes": [],
     "cursos": [],
     "turmas": [],
     "financas": [],

}

const recepcionista = {
     "id_instituicao": "",
     "id_escola": "",
     "nome": "Mulher-Maravilha",
     "sobrenome": "Themyscira",
     "status": "ATIVO",
     "imagem_perfil": "http://",
     "data_cadastro": "",
     "ultima_atualizacao": "",
     "idioma": "PORTUGUÊS",
     "aplicaDesconto": true,
     "desconto_max": 10,
     "cpf": "39867245083",
     "rg": "185407766",
     "data_nascimento":"20/10/1988",
     "telefone":"11993747829",
     "email": "mulhermaravilha@dc.com",
     "perfis": ["RECEPCIONISTA"],
     "perfil_atual": "RECEPCIONISTA",
     "senha": "",
     "pais": "Brasil",
     "estado": "São paulo",
     "cidade": "São paulo",
     "bairro": "Ibirapuera",
     "logradouro": "Av Ibirapuera",
     "numero": 1000,
     "cep": "05892470",
     "financas": [],

}